name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm i
      - run: npm run check
      - run: npm run test
      - run: npm run demo:init
      - run: npm run e2e
